export const lightThemeVars = {
    '--background-color': '#fff',
    '--content-background-color': '#f4f7fa',
    '--modal-backcolor': '#FFFFFF',
    '--select-hover-backcolor': '#F3F3F3',
    '--text-color': '#515a6e',
    '--checked-color': '#007BFF',
    '--date-hover-color': '#E1F0FE',
    '--graph-item-backcolor': '#f4f7fa',
    '--debt-backcolor': '#f4f7fa',
    '--debt-text-color': '#133685',
    '--graph-hover-color': '#ceced0',
    '--table-hover': '#EBF7FF',
    '--border': '#dadadd',
    '--table-th': '#fff',
    '--table-th-border': '',
    '--table-highlight': '#d4d9e8',
    '--scroller': '#8f959b',
    '--scroller-hover': 'rgba(159, 158, 158, 0.8)',
}